### PR TITLE
 * fix: debian origins since archive name changes, moved to codename …

### LINKED ISSUE #145: incorrect Debian OS origin string
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: v4.0.0

## How to reproduce (e.g Puppet code you use)

Include the unattended upgrades class without additional parameters.

```
class profile::debian {
  include unattended_upgrades
}
```

## What are you seeing

https://github.com/voxpupuli/puppet-unattended_upgrades/blob/v4.0.0/manifests/params.pp#L71

This line sets the `origins` for Debian 9 stretch to `origin=Debian,archive=stable,label=Debian-Security`. However, as of July 2019, Debian 9 stretch is no longer 'stable' but 'oldstable' and Debian 10 buster is now stable.

## What behaviour did you expect instead

The origin string for Debian 9 stretch should be `origin=Debian,archive=oldstable,label=Debian-Security`

## Output log

N/A

## Any additional information you'd like to impart

I believe this is a simple fix of changing the names in the `manifests/params.pp` file. However, one may want to consider using the distribution `codename` in the string which may be more resistant to changes, i.e., when Debian upgrades what is considered 'stable'.

See these commits  for the last time this changed (2017): c20f1fcc99b207fd3cb9a8b08d7039b0128c2fef & 5fe39f89506c5737fcfa90efbbea43b10fbd88f5; also PR #102 .

### PR DESCRIPTION
**Pull request by deubert-it**
…based filter for future proofing #145

#### Pull Request (PR) description
Debian changed apt repository archive names some weeks ago, this PR adapts the module to that and switches to codename (jessie/stretch/buster etc.) based origin filtering for debian based systems, so it should be more stable in the future.

#### This Pull Request (PR) fixes the following issues
Fixes #145

### CODE REVIEW

**Comment by drshawnkwang** [comment]
Thank  you for putting together this PR. I"m not a committer (just someone who noticed the bug), but I do have some Debian 8 and 9 servers I can see about testing this code on. Hopefully I can find some time next week to do that.

File: spec/classes/debian_spec.rb [hunk 1]
```diff
@@ -134,7 +135,22 @@
...
+            it do
+              is_expected.to create_file(file_unattended).with(
+                owner: 'root',
+                group: 'root',
+                mode: '0644'
+              ).with_content(
+                # This section varies for different releases
+                /\Unattended-Upgrade::Origins-Pattern\ {\n
+                \t"origin=Debian,codename=\${distro_codename},label=Debian-Security";\n
                 };/x
```
Comment (gfa) [inline spec/classes/debian_spec.rb]: This is not correct, the default origins for buster are
```
"origin=Debian,codename=${distro_codename},label=Debian";
"origin=Debian,codename=${distro_codename},label=Debian-Security";
```

https://www.debian.org/releases/buster/amd64/release-notes/ch-whats-new.en.html#unattended-upgrades

Comment (gfa) [reply spec/classes/debian_spec.rb]: With those changes the PR works for me

Comment (deubert-it) [reply spec/classes/debian_spec.rb]: Thank you for your review. I thought this was some rule the module author implemented for unknown reasons, but with your provided link it makes much more sense. I'll happily make the changes.

**Comment by Scifire** [comment]
Would say this is also related to #150, any reason why this is not merged?

**Comment by igalic** [comment]
any or all of 

- lack of volunteers
- lack of volunteer time
- "wrong" priorisation (of the above)
- it was overlooked

File: manifests/params.pp [hunk 2]
```diff
@@ -48,33 +48,26 @@
...
-                                  '${distro_id} ${distro_codename}-lts',] #lint:ignore:single_quote_string_with_variables
-        }
-        'wheezy': {
-          $legacy_origin      = false
+        'squeeze', 'wheezy': {
+          $legacy_origin      = true
           $origins            = [
-            'origin=Debian,archive=oldoldstable,label=Debian-Security',
+            '${distro_id} ${distro_codename}-security', #lint:ignore:single_quote_string_with_variables
+            '${distro_id} ${distro_codename}-lts', #lint:ignore:single_quote_string_with_variables
```
Comment (igalic) [inline manifests/params.pp]: if these are facts, and they suspiciously look like facts, then i would address them as `$facts[name]`
but if the entire class, or module, addresses them that way, we can keep that for another pr

**Comment by Scifire** [comment]
@igalic well it was more like " I don´t see any open issues with this PR, maybe there is one which I didn´t see" ;-)

File: spec/classes/debian_spec.rb [hunk 3]
```diff
@@ -134,7 +135,23 @@
...
+        when 'buster'
+          context 'with defaults on Debian 10 Buster' do
+            it do
+              is_expected.to create_file(file_unattended).with(
+                owner: 'root',
+                group: 'root',
+                mode: '0644'
+              ).with_content(
+                # This section varies for different releases
+                /\Unattended-Upgrade::Origins-Pattern\ {\n
```
Comment (igalic) [inline spec/classes/debian_spec.rb]: why is `U` `\`ed?

File: manifests/params.pp (hunk 2 above)
Comment (thechristschn) [reply manifests/params.pp]: Those aren't facts, they are macros from apt which should be like this in the config file.

Comment (gfa) [reply manifests/params.pp]: Those are not facts (although they look like) unattended upgrades uses variables instead of distribution names by default on its configuration, eg `$distro_codename` instead of `buster`

we could use facts and write `buster` but it wont be the most common way of configuring unattended upgrades (it will work anyway)

Comment (igalic) [reply manifests/params.pp]: aaaaaaaaah, hence the `'` single `'` quotes.

**Comment by igalic** [comment]
> @igalic well it was more like " I don´t see any open issues with this PR, maybe there is one which I didn´t see" ;-)

sometimes we get issues,
sometimes we get PRs,
sometimes we get both,
and sometimes we get neither.

(i'm feeling very poetical right now ;)

File: spec/classes/debian_spec.rb (hunk 3 above)
Comment (deubert-it) [reply spec/classes/debian_spec.rb]: Hi @igalic, I don't know that construct by hand to be honest, I copied it from other places in the same file.

For me it looks like a multiline regex definition. Maybe they are needed to mask possible regex characters like `-` and `:` in the whole phrase `\Unattended-Upgrade::Origins-Pattern\` ?

**Comment by anarcat** [comment]
we need this in our deployment so i'll likely merge this after another positive review.

thanks!

File: spec/classes/debian_spec.rb (hunk 3 above)
Comment (anarcat) [reply spec/classes/debian_spec.rb]: since we already use this elsewhere, it seems fair to accept this.

**Comment by hiromipaw** [comment]
:+1: would be nice to see this merged upstream in the near future.
